            - name: validate-license-action
  # You may pin to the exact commit or the version.
  # uses: datreeio/validate-license-action@69e5b55debf4046461b0d21cced2f444937f863f
  uses: datreeio/validate-license-action@v1.0.0
          
